### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by AviKKi** [itaditya/react-hook-recipes#6]
Currently it looks like this in a mobile device, it would be much better if usage is shown below implementation in small devices, @itaditya I would like to work on this #hacktoberfest assign it to me.
![Screenshot_20191009-062518](https://user-images.githubusercontent.com/34864662/66443696-ad306980-ea5d-11e9-8a72-de6290373138.png)

**Comment by itaditya** [comment]
This would be a very valuable contribution. @AviKKi go ahead and let me know if you get stuck anywhere

**Comment by AviKKi** [comment]
just with some minimal changes it looks much better than before
![Screenshot from 2019-10-13 14-55-45](https://user-images.githubusercontent.com/34864662/66713594-3af7b600-edca-11e9-8337-a5e138d98318.png)
![Uploading Screenshot from 2019-10-13 14-55-51.png…]()
Heres my PR #7
